### ISSUE TITLE
Bots can't send messages to other bots

### ISSUE THREAD

**Issue by DanCousins** [fjwillemsen/Apple-Store-Stock-Notifier#6]
Hi there, trying to grab a new 15PM using your utility, but running into some issues with the telegram portion.

I've created an app, created a bot, punched in all my details.

`Traceback (most recent call last):
  File "/home/dan/python/Apple-Store-Stock-Notifier/monitor.py", line 350, in <module>
    monitor = Monitor()
  File "/home/dan/python/Apple-Store-Stock-Notifier/monitor.py", line 170, in __init__
    client.loop.run_until_complete(self.start_monitoring(client))
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/dan/python/Apple-Store-Stock-Notifier/monitor.py", line 180, in start_monitoring
    await send(client, message)
  File "/home/dan/python/Apple-Store-Stock-Notifier/utils.py", line 20, in send
    await client.send_message(username, message)
  File "/home/dan/.local/lib/python3.10/site-packages/telethon/client/messages.py", line 853, in send_message
    result = await self(request)
  File "/home/dan/.local/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/dan/.local/lib/python3.10/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcerrorlist.UserIsBotError: Bots can't send messages to other bots (caused by SendMessageRequest)`

Hope you can help, 
Thanks

**Comment by kaktus210** [comment]
have same error

**Comment by fruitcoder** [comment]
Update the telethon version to `1.30.3` and rerun `pip` (and delete the last session)

**Comment by ptrhnsn** [comment]
Same error here
